# -*- coding: utf-8 -*-
"""
parser/narrative_commands.py — PC narrative memory commands.

Commands:
  +background         — show your background
  +background <text>  — set your background (player-written)
  +recap              — show your narrative recap (recent actions + background)
  +quests             — show your active personal quests
"""
import logging
from parser.commands import BaseCommand, CommandContext

log = logging.getLogger(__name__)


class BackgroundCommand(BaseCommand):
    key = "+background"
    aliases = ["background", "+bg", "bg"]
    help_text = (
        "View or set your character background.\n"
        "\n"
        "USAGE:\n"
        "  +background           — show your current background\n"
        "  +background <text>    — set your background (up to 2000 chars)\n"
        "\n"
        "Your background is seen by NPCs during conversation and by the\n"
        "Director AI when generating personal quests. Write it in third\n"
        "person — who you are, where you came from, what drives you.\n"
        "\n"
        "EXAMPLE:\n"
        "  +background A former Imperial TIE pilot who defected after\n"
        "  witnessing the destruction of an innocent colony. Now works\n"
        "  as a freelance pilot, taking jobs that don't involve civilians."
    )
    usage = "+background [<text>]"

    async def execute(self, ctx: CommandContext):
        from engine.narrative import get_background, set_background

        char = ctx.session.character
        text = (ctx.args or "").strip()

        if not text:
            bg = await get_background(ctx.db, char["id"])
            if bg:
                await ctx.session.send_line(
                    f"\n  \033[1;33mYour background:\033[0m\n  {bg}\n"
                )
            else:
                await ctx.session.send_line(
                    "  You haven't written a background yet.\n"
                    "  Use \033[1;33m+background <text>\033[0m to set one."
                )
            return

        await set_background(ctx.db, char["id"], text)
        await ctx.session.send_line(
            f"  \033[1;32mBackground saved.\033[0m "
            f"({len(text)} chars)  NPCs and the Director will take note."
        )


class RecapCommand(BaseCommand):
    key = "+recap"
    aliases = ["recap", "+history"]
    help_text = (
        "Show your narrative recap — recent actions, background, and personal quests.\n"
        "The Director AI uses this information to generate story hooks tailored to you."
    )
    usage = "+recap"

    async def execute(self, ctx: CommandContext):
        from engine.narrative import format_recap
        char = ctx.session.character
        await ctx.session.send_line(await format_recap(ctx.db, char))


class QuestsCommand(BaseCommand):
    key = "+quests"
    aliases = ["quests", "+pq", "personalquests"]
    help_text = (
        "Show your active personal quests.\n"
        "Personal quests are generated by the Director AI based on your history.\n"
        "\n"
        "USAGE:\n"
        "  +quests              — show active quests\n"
        "  +quests completed    — show completed quests\n"
        "  questaccept <id>     — accept a pending quest\n"
        "  questcomplete <id>   — mark a quest complete (Director verifies)\n"
        "  questabandon <id>    — abandon a quest"
    )
    usage = "+quests [completed]"

    async def execute(self, ctx: CommandContext):
        char = ctx.session.character
        args = (ctx.args or "").strip().lower()
        status = "complete" if args == "completed" else "active"

        quests = await ctx.db.get_personal_quests(char["id"], status=status)

        if not quests:
            label = "completed" if status == "complete" else "active"
            await ctx.session.send_line(
                f"  You have no {label} personal quests.\n"
                f"  The Director AI generates quests based on your recent activity.\n"
                f"  Keep playing — quests appear as your story develops."
            )
            return

        lines = [
            "\033[1;36m══════════════════════════════════════════\033[0m",
            f"  \033[1;37mPERSONAL QUESTS — {'ACTIVE' if status == 'active' else 'COMPLETED'}\033[0m",
            "\033[1;36m──────────────────────────────────────────\033[0m",
        ]
        for q in quests:
            status_icon = "\033[1;32m✓\033[0m" if q["status"] == "complete" else "\033[1;35m▸\033[0m"
            lines.append(f"  {status_icon} [{q['id']}] \033[1;37m{q['title']}\033[0m")
            if q.get("description"):
                lines.append(f"    \033[2m{q['description'][:120]}\033[0m")
        lines.append("\033[1;36m══════════════════════════════════════════\033[0m")
        await ctx.session.send_line("\n".join(lines))


def register_narrative_commands(registry):
    registry.register(BackgroundCommand())
    registry.register(RecapCommand())
    registry.register(QuestsCommand())
