"""
build_gcw_yamls.py — author the data/worlds/gcw/*.yaml counterpart files
by reading the legacy GCW source-of-truth out of engine/world_lore.py
and engine/director.py.

The output YAMLs are byte-equivalent (at the parsed-dict level) to the
legacy hardcoded constants. They are the regression-test asset that
Drop 6a.2 and 6a.3 require to gate the engine refactor.

Run from inside the SW_MUSH repo root:
    python3 build_gcw_yamls.py

Outputs:
    data/worlds/gcw/lore.yaml
    data/worlds/gcw/director_config.yaml
    data/worlds/gcw/ambient_events.yaml
    data/worlds/gcw/era.yaml
"""

from __future__ import annotations

import ast
import importlib.util
import io
import os
import sys
from pathlib import Path

import yaml


# ── Source-of-truth extraction ────────────────────────────────────────────────


def load_seed_entries(repo_root: Path) -> list[dict]:
    """Import engine/world_lore.py and pull SEED_ENTRIES."""
    src_path = repo_root / "engine" / "world_lore.py"
    spec = importlib.util.spec_from_file_location("world_lore_src", str(src_path))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return list(mod.SEED_ENTRIES)


def load_director_constants(repo_root: Path) -> dict:
    """AST-extract director.py constants without triggering its imports."""
    src = (repo_root / "engine" / "director.py").read_text()
    tree = ast.parse(src)
    wanted = {
        "VALID_FACTIONS",
        "VALID_ZONES",
        "DEFAULT_INFLUENCE",
        "MIN_INFLUENCE",
        "MAX_INFLUENCE",
        "MAX_DELTA",
        "FACTION_TURN_INTERVAL",
        "ERA_MILESTONES",
    }
    ns: dict = {}
    for node in tree.body:
        if isinstance(node, ast.Assign):
            for tgt in node.targets:
                if isinstance(tgt, ast.Name) and tgt.id in wanted:
                    code = ast.get_source_segment(src, node)
                    exec(code, ns)
    # Also pull the system_prompt out of the source. It's defined as a
    # local string inside a method, so we have to parse it as a literal.
    prompt = _extract_system_prompt(src)
    ns["SYSTEM_PROMPT"] = prompt
    return ns


def _extract_system_prompt(src: str) -> str:
    """Grab the multi-line concatenated string assigned to system_prompt."""
    tree = ast.parse(src)
    for node in ast.walk(tree):
        if (
            isinstance(node, ast.Assign)
            and len(node.targets) == 1
            and isinstance(node.targets[0], ast.Name)
            and node.targets[0].id == "system_prompt"
            and isinstance(node.value, (ast.Constant, ast.JoinedStr, ast.BinOp))
        ):
            # Use ast.literal_eval where possible, otherwise fall back
            # to evaluating the source segment.
            try:
                return ast.literal_eval(node.value)
            except Exception:
                code = ast.get_source_segment(src, node)
                ns: dict = {}
                exec(code, ns)
                return ns["system_prompt"]
    raise RuntimeError("Could not find system_prompt in director.py")


# ── YAML dumper helpers ───────────────────────────────────────────────────────


class _LiteralStr(str):
    """Tag class so our representer can emit folded-block style for content."""


def _literal_representer(dumper, data):
    return dumper.represent_scalar(
        "tag:yaml.org,2002:str", str(data), style=">"
    )


class _BlockStr(str):
    """Tag for multi-line strings emitted as literal blocks (|)."""


def _block_representer(dumper, data):
    return dumper.represent_scalar(
        "tag:yaml.org,2002:str", str(data), style="|"
    )


def _make_dumper():
    """A SafeDumper that preserves dict insertion order, no aliasing."""
    class GcwDumper(yaml.SafeDumper):
        pass

    GcwDumper.add_representer(_LiteralStr, _literal_representer)
    GcwDumper.add_representer(_BlockStr, _block_representer)

    # Disable aliasing so repeated values get re-emitted (cleaner reads)
    def _ignore_aliases(self, data):
        return True

    GcwDumper.ignore_aliases = _ignore_aliases
    return GcwDumper


# ── lore.yaml ─────────────────────────────────────────────────────────────────


LORE_HEADER = """\
# data/worlds/gcw/lore.yaml
# Galactic Civil War Era — World Lore Corpus
# Schema version 1
#
# This file is the GCW counterpart to data/worlds/clone_wars/lore.yaml.
# It is BYTE-EQUIVALENT (at the parsed-dict level) to the legacy
# SEED_ENTRIES list in engine/world_lore.py — the source-of-truth for
# the GCW seed data prior to era-parameterization.
#
# Generated by build_gcw_yamls.py from engine/world_lore.py SEED_ENTRIES
# at the time Drop 6a.5 was authored. When Drop 6a.2 lands and engine/
# world_lore.py reads from era YAML, this file becomes the live data.
# Until then, it is the regression-test asset that proves byte-equivalence.
#
# Schema mirrors the world_lore SQLite table + SEED_ENTRIES dict shape:
#   title         str        unique entry title
#   keywords      str        comma-separated trigger terms (lowercased)
#   content       str        the lore text (1-3 paragraphs typical)
#   category      str        faction | location | history | item | npc |
#                            character | species
#   zone_scope    str|null   comma-separated zone keys (entries trigger
#                            preferentially in matching zones; null = global)
#   priority      int        3-9; higher = more prominent in retrieval
#
# Source counts at generation time:
#   - 64 entries total
#   - 20 zone-scoped, 44 global
#   - Categories: faction, location, history, item, npc, character, species

schema_version: 1

entries:
"""


def write_lore_yaml(seed_entries: list[dict], out: Path) -> None:
    """Write the 64 GCW lore entries with the same field order as CW lore.yaml.

    CW shape: title, keywords, category, priority, [zone_scope], content
    Content uses folded-block style (>) so multi-paragraph text reads well.
    """
    Dumper = _make_dumper()

    # Build ordered entries with the CW field order
    entries_out = []
    for entry in seed_entries:
        record = {
            "title": entry["title"],
            "keywords": entry["keywords"],
            "category": entry["category"],
            "priority": entry["priority"],
        }
        if "zone_scope" in entry:
            record["zone_scope"] = entry["zone_scope"]
        record["content"] = _LiteralStr(entry["content"])
        entries_out.append(record)

    body = yaml.dump(
        entries_out,
        Dumper=Dumper,
        sort_keys=False,
        default_flow_style=False,
        allow_unicode=True,
        width=78,
    )

    # The dump emits a top-level list with `- key: ...` form. We want this
    # nested under `entries:` with a 2-space indent — matching CW shape.
    indented = "\n".join("  " + line if line else "" for line in body.splitlines())

    out.write_text(LORE_HEADER + indented + "\n")


# ── director_config.yaml ─────────────────────────────────────────────────────


DIRECTOR_HEADER = """\
# data/worlds/gcw/director_config.yaml
# Galactic Civil War Era — Director AI Configuration
# Schema version 1
#
# This file is the GCW counterpart to
# data/worlds/clone_wars/director_config.yaml. It is BYTE-EQUIVALENT
# (at the parsed-dict level) to the legacy hardcoded values in
# engine/director.py:
#   - VALID_FACTIONS frozenset (line 48)        → valid_factions
#   - VALID_ZONES frozenset (line 51-54)        → zone_baselines.keys()
#   - DEFAULT_INFLUENCE dict (line 57-64)       → zone_baselines
#   - MIN_INFLUENCE / MAX_INFLUENCE             → influence_min/max
#   - MAX_DELTA (line 71)                       → max_delta_per_turn
#   - FACTION_TURN_INTERVAL (line 45)           → faction_turn_interval_seconds
#   - system_prompt (lines 678-751)             → system_prompt
#   - ERA_MILESTONES (lines 82-105)             → milestone_events
#
# Generated by build_gcw_yamls.py from engine/director.py at the time
# Drop 6a.5 was authored. When Drop 6a.3 lands and engine/director.py
# reads from era YAML, this file becomes the live data for active_era==gcw.
#
# Note: GCW has no holonet_news_pool (CW-specific atmospheric flavor) and
# no rewicker map (GCW IS the legacy axis — nothing to translate to).
# Both keys are omitted entirely rather than emitted as empty containers.

schema_version: 1

"""


def write_director_config_yaml(consts: dict, out: Path) -> None:
    """Build a CW-shape director_config.yaml from director.py constants."""
    Dumper = _make_dumper()

    # 1. Faction model
    valid_factions = sorted(consts["VALID_FACTIONS"])  # canonical order
    npc_only_factions: list = []  # GCW has no NPC-only factions

    # 2. Zone baselines — keep the source insertion order (DEFAULT_INFLUENCE)
    zone_baselines = {}
    for zone, scores in consts["DEFAULT_INFLUENCE"].items():
        # Preserve faction order from VALID_FACTIONS canonical sort
        zone_baselines[zone] = {f: scores[f] for f in valid_factions}

    # 3. System prompt — emit as block literal for readability
    system_prompt = _BlockStr(consts["SYSTEM_PROMPT"])

    # 4. Milestone events — convert ERA_MILESTONES tuples to structured records
    milestone_events = []
    for (faction, threshold, era_key, headline, event_type, duration_min) in consts["ERA_MILESTONES"]:
        # Distinguish "low-watermark" milestones (imperial_retreat: < 30)
        # from "high-watermark" (most others).
        # The tuple shape doesn't encode direction; we infer from era_key.
        # imperial_retreat is the only "below" milestone — flag it.
        is_below = era_key == "imperial_retreat"
        record = {
            "id": era_key,
            "trigger": {
                "type": "faction_avg_influence",
                "faction": faction,
                "threshold": threshold,
                "direction": "below" if is_below else "above",
            },
            "headline": headline,
            "fires_once": True,  # ERA_MILESTONES are one-time events
        }
        if event_type:
            record["narrative_event_type"] = event_type
        if duration_min:
            record["duration_minutes"] = duration_min
        milestone_events.append(record)

    config = {
        "valid_factions": valid_factions,
        "npc_only_factions": npc_only_factions,
        "influence_min": consts["MIN_INFLUENCE"],
        "influence_max": consts["MAX_INFLUENCE"],
        "max_delta_per_turn": consts["MAX_DELTA"],
        "faction_turn_interval_seconds": consts["FACTION_TURN_INTERVAL"],
        "zone_baselines": zone_baselines,
        "system_prompt": system_prompt,
        "milestone_events": milestone_events,
    }

    body = yaml.dump(
        config,
        Dumper=Dumper,
        sort_keys=False,
        default_flow_style=False,
        allow_unicode=True,
        width=120,
    )

    # Reformat the zone_baselines block to use inline-flow style for readability
    # (matches the CW director_config.yaml style)
    body = _inline_zone_baselines(body, zone_baselines)

    out.write_text(DIRECTOR_HEADER + body)


def _inline_zone_baselines(body: str, zone_baselines: dict) -> str:
    """Rewrite the zone_baselines block to inline-flow style."""
    lines = body.split("\n")
    out_lines: list[str] = []
    i = 0
    while i < len(lines):
        line = lines[i]
        if line.rstrip() == "zone_baselines:":
            out_lines.append(line)
            i += 1
            # Skip until we hit the next top-level key (no leading spaces)
            # while emitting inline-flow zone records
            for zone, scores in zone_baselines.items():
                inline = ", ".join(f"{f}: {v}" for f, v in scores.items())
                out_lines.append(f"  {zone}: {{ {inline} }}")
            # Skip the original block-style emissions
            while i < len(lines) and (lines[i].startswith("  ") or lines[i] == ""):
                # stop at first non-indented line that's not blank
                if lines[i].strip() == "":
                    if i + 1 < len(lines) and lines[i + 1].startswith("  "):
                        i += 1
                        continue
                    else:
                        break
                if not lines[i].startswith("  "):
                    break
                i += 1
        else:
            out_lines.append(line)
            i += 1
    return "\n".join(out_lines)


# ── ambient_events.yaml ──────────────────────────────────────────────────────


AMBIENT_HEADER = """\
# data/worlds/gcw/ambient_events.yaml
# Galactic Civil War Era — Ambient Room Events
# Schema version 1
#
# This file is the GCW counterpart to
# data/worlds/clone_wars/ambient_events.yaml. It is BYTE-EQUIVALENT to
# the legacy data/ambient_events.yaml at the time Drop 6a.5 was authored.
#
# When Drop 6a.4 lands and engine/ambient_events.py reads from era YAML,
# this file becomes the live ambient pool for active_era==gcw. Until then,
# it is the regression-test asset for byte-equivalence.
#
# The CW ambient_events.yaml authors per-zone keys (e.g. coruscant_senate);
# this GCW file authors the legacy generic keys: spaceport, streets,
# cantina, shops, jabba, government, default. Engine refactor 6a.4 makes
# the merge logic era-aware so both shapes coexist.

schema_version: 1

ambient_events:
"""


def write_ambient_events_yaml(global_path: Path, out: Path) -> None:
    """Mirror data/ambient_events.yaml under data/worlds/gcw/ambient_events.yaml.

    The legacy file uses bare top-level keys (spaceport: [], streets: [], ...).
    The CW counterpart wraps them under `ambient_events:`. We adopt the CW shape
    for consistency.
    """
    legacy = yaml.safe_load(global_path.read_text())

    Dumper = _make_dumper()
    body = yaml.dump(
        legacy,
        Dumper=Dumper,
        sort_keys=False,
        default_flow_style=False,
        allow_unicode=True,
        width=120,
    )
    indented = "\n".join("  " + line if line else "" for line in body.splitlines())
    out.write_text(AMBIENT_HEADER + indented + "\n")


# ── era.yaml ─────────────────────────────────────────────────────────────────


ERA_YAML = """\
# data/worlds/gcw/era.yaml
# Galactic Civil War Era — Foundation Configuration
# Schema version 1 — per world_data_extraction_design_v1.md §5
#
# This file is the GCW counterpart to data/worlds/clone_wars/era.yaml.
# It registers the GCW lore/director_config/ambient_events YAMLs so the
# era loader picks them up when active_era == gcw.
#
# Until Drop 6a.2/6a.3/6a.4 ship, this file is inert at runtime — the
# engine still reads SEED_ENTRIES, DEFAULT_INFLUENCE, etc. from
# hardcoded constants in engine/world_lore.py and engine/director.py.
# The era YAML is the regression-test asset proving byte-equivalence.

schema_version: 1

era:
  code: gcw
  name: "Galactic Civil War"
  tagline: "The Empire stands. The Rebellion fights. The galaxy chooses sides."
  description: >
    Approximately 0 ABY, between A New Hope and The Empire Strikes Back.
    The Galactic Empire rules through fear; the Rebel Alliance fights from
    hidden bases. The Hutt Cartel profits from both sides. Mos Eisley is
    a backwater spaceport on Tatooine where Imperial authority is thin
    and the Hutts hold real power.
  timeline_reference: "~0 ABY"
  canon_era: "Galactic Civil War (Original Trilogy)"
  sourcebook_refs:
    - "WEG40092 (Imperial Sourcebook)"
    - "WEG40069 (GG7 Mos Eisley)"
    - "WEG40124 (GG1 A New Hope)"
    - "WEG40027 (GG6 Tramp Freighters)"
    - "WEG40048 (GM Screen)"
    - "WEG40093 (SW Sourcebook 2nd Ed)"

policy:
  # ── Force policy ─────────────────────────────────────────────────────────
  # GCW: Jedi Order is destroyed. Force-sensitives are hunted. Public Force
  # use draws Imperial attention. Lightsabers are extreme contraband.
  force_chargen_allowed: false
  force_sensitive_chargen: forbidden       # No PC Jedi in GCW launch scope
  lightsaber_availability: extreme_contraband
  force_suppression: inquisitorial         # Active Imperial pressure
  dark_side_detectability: medium

  # ── Faction set ──────────────────────────────────────────────────────────
  # Must match VALID_FACTIONS frozenset in engine/director.py.
  factions:
    - imperial
    - rebel
    - criminal
    - independent
  npc_only_factions: []

  # ── Starting defaults ────────────────────────────────────────────────────
  starting_room_slug: westport_arrivals
  starting_faction: independent
  starting_credits_default: 500

  # ── Era flavor ──────────────────────────────────────────────────────────
  default_trooper_type: stormtrooper
  default_imperial_substitute: imperial    # GCW IS the imperial axis
  default_rebel_substitute: rebel
  hutt_cartel_stance: criminal_dominant

  # ── Director AI knobs ────────────────────────────────────────────────────
  director_config_ref: director_config.yaml

content_refs:
  zones: zones.yaml                        # GCW zones — TBD; engine reads from build_mos_eisley.py today
  organizations: organizations.yaml        # GCW orgs — TBD; engine reads from data/organizations.yaml today
  planets: []                              # Mos Eisley is single-planet at GCW launch

  # ── Director / Lore data-fication (Drop 6a) ─────────────────────────────
  # These three files are consumed by Drop 6a's engine refactor. Until 6a.2
  # /6a.3/6a.4 land, they are inert at runtime — engine still reads from
  # source constants. They are the regression-test asset proving byte-
  # equivalence at the parsed-dict level.
  lore: lore.yaml
  director_config: director_config.yaml
  ambient_events: ambient_events.yaml

# ═══════════════════════════════════════════════════════════════════════
# REGISTRY POLICY
# ═══════════════════════════════════════════════════════════════════════
# GCW uses the global data/starships.yaml unfiltered. No exclusions.
registry_policy:
  starship_excluded_templates: []

# Policy enforcement flags — advisory until Drop 0 lands the world-extraction
# refactor. CW already enforces several of these.
policy_enforcement:
  force_chargen_allowed_is_enforced: true
  force_sensitive_chargen_is_enforced: true
  lightsaber_availability_is_enforced: true
  starting_faction_is_enforced: true
"""


def write_era_yaml(out: Path) -> None:
    out.write_text(ERA_YAML)


# ── main ─────────────────────────────────────────────────────────────────────


def main():
    repo_root = Path(__file__).resolve().parent
    if not (repo_root / "engine" / "director.py").is_file():
        # Allow running from /home/claude/drop_6a5 against an external repo
        repo_root = Path(os.environ.get("SW_MUSH_REPO", "/home/claude/sw_mush/SW_MUSH"))
    if not (repo_root / "engine" / "director.py").is_file():
        print(f"ERROR: cannot find engine/director.py — set SW_MUSH_REPO=...", file=sys.stderr)
        sys.exit(1)

    out_dir = Path(__file__).resolve().parent / "data" / "worlds" / "gcw"
    out_dir.mkdir(parents=True, exist_ok=True)

    print(f"Reading source from: {repo_root}")
    print(f"Writing output to:   {out_dir}")
    print()

    # 1. Lore
    seed_entries = load_seed_entries(repo_root)
    write_lore_yaml(seed_entries, out_dir / "lore.yaml")
    print(f"  ✓ lore.yaml             ({len(seed_entries)} entries)")

    # 2. Director config
    consts = load_director_constants(repo_root)
    write_director_config_yaml(consts, out_dir / "director_config.yaml")
    print(f"  ✓ director_config.yaml  ({len(consts['DEFAULT_INFLUENCE'])} zones, "
          f"{len(consts['VALID_FACTIONS'])} factions, "
          f"{len(consts['ERA_MILESTONES'])} milestones)")

    # 3. Ambient events
    write_ambient_events_yaml(repo_root / "data" / "ambient_events.yaml",
                              out_dir / "ambient_events.yaml")
    print(f"  ✓ ambient_events.yaml")

    # 4. Era root config
    write_era_yaml(out_dir / "era.yaml")
    print(f"  ✓ era.yaml")

    print()
    print("Build complete.")


if __name__ == "__main__":
    main()
