#!/usr/bin/env python3
"""tools/make_interior_zonemap.py — generate per-building INTERIOR AreaGeometry
zone-map YAMLs from real planet room map_x/map_y, for the Nano interior-plate
drafts (2026-06-19).

Drafts-only test scaffolding: writes under static/tools/_interior_test/clone_wars/
maps/ (OUTSIDE data/worlds/, so it never trips the additive guard and is not a
phantom unconsumed live file). Mirrors the hand-authored jedi_temple.yaml pattern
so tools/make_substrate_seed.py renders an honest seed.

Projection (matches jedi_temple.yaml + the live north-up projector):
  world_x = MARGIN + (gx - min_gx)*CELL + CELL/2     (+ sub-offset for cell collisions)
  world_y = MARGIN + (max_gy - gy)*CELL + CELL/2     (HIGHER map_y -> LOWER world y)
Rooms become footprints; intra-zone exits become L-bend corridors; landmark_ids
mark distinctive chambers; >=6-room interiors get simple horizontal tier-bands.

Usage:
  python tools/make_interior_zonemap.py [--spec static/tools/_interior_test/interiors_spec.json] [--only key1,key2]
"""
from __future__ import annotations
import argparse
import json
from pathlib import Path

CELL = 2.0
MARGIN = 1.0
OUT_DIR = Path("static/tools/_interior_test/clone_wars/maps")
BAND_NAMES = {2: ["LOWER LEVEL", "UPPER LEVEL"],
              3: ["LOWER LEVEL", "MID LEVEL", "UPPER LEVEL"]}


def _g(v: float) -> str:
    return f"{round(v, 2):g}"


def project(rooms):
    gxs = [r["map_x"] for r in rooms]
    gys = [r["map_y"] for r in rooms]
    min_gx, max_gx = min(gxs), max(gxs)
    min_gy, max_gy = min(gys), max(gys)
    by_cell = {}
    for r in rooms:
        by_cell.setdefault((r["map_x"], r["map_y"]), []).append(r)
    pos = {}
    for (gx, gy), group in by_cell.items():
        n = len(group)
        for i, r in enumerate(group):
            sub = 0.0 if n == 1 else (i - (n - 1) / 2) * (CELL * 0.5 / n)
            wx = MARGIN + (gx - min_gx) * CELL + CELL / 2 + sub
            wy = MARGIN + (max_gy - gy) * CELL + CELL / 2
            pos[r["id"]] = (wx, wy, n)
    x_max = MARGIN * 2 + (max_gx - min_gx + 1) * CELL
    y_max = MARGIN * 2 + (max_gy - min_gy + 1) * CELL
    return pos, x_max, y_max


def footprint(room_id, hub, lms, collide):
    if collide > 1:
        return 0.9, 0.7
    if room_id == hub:
        return 1.5, 1.15
    if room_id in lms:
        return 1.35, 1.05
    return 1.2, 0.95


def gen(entry) -> str:
    rooms = entry["rooms"]
    pos, x_max, y_max = project(rooms)
    hub = entry.get("hub")
    lms = set(entry.get("landmark_ids") or [])
    by_id = {r["id"]: r for r in rooms}

    L = []
    L.append("# " + "-" * 73)
    L.append(f"# {entry['planet']} — {entry['display_name']} INTERIOR (AreaGeometry, TEST zone-map)")
    L.append("#")
    L.append("# Generated by tools/make_interior_zonemap.py from the planet file's real")
    L.append(f"# interior rooms (map_x/map_y) projected into a building floorplan. Nano")
    L.append("# interior-plate DRAFT — lives OUTSIDE data/worlds/ (test scaffolding, not")
    L.append("# wired into the live game). Fed to tools/make_substrate_seed.py via --root.")
    L.append("# " + "-" * 73)
    L.append("")
    L.append("schema_version: 1")
    L.append(f"area_key: {entry['planet'].lower()}.{entry['key']}")
    L.append(f"display_name: {entry['display_name']}")
    L.append(f"planet: {entry['planet']}")
    L.append("era: 20 BBY · Clone Wars")
    L.append("default_terrain: stone")
    L.append(f"palette: {entry['key']}")
    L.append("")
    L.append("bounds:")
    L.append("  x_min: 0.0")
    L.append("  y_min: 0.0")
    L.append(f"  x_max: {_g(x_max)}")
    L.append(f"  y_max: {_g(y_max)}")
    L.append("")

    # districts (tier bands) — ALWAYS emitted so every room has a valid `zone`
    # (the live area_loader requires it): banded for >=6-room interiors, else a
    # single "interior" district covering the bounds.
    y_bot, y_top = 0.4, round(y_max - 0.4, 2)
    x0, x1 = 0.4, round(x_max - 0.4, 2)
    if len(rooms) >= 6:
        nb = 3 if (y_max > 8.5) else 2
        names = BAND_NAMES[nb]
    else:
        nb, names = 1, ["INTERIOR"]
    bh = (y_top - y_bot) / nb
    bands = []  # (district_id, y0, y1) bottom -> top
    L.append("districts:")
    for i in range(nb):
        y0 = round(y_bot + i * bh, 2)
        y1 = round(y_bot + (i + 1) * bh, 2)
        did = names[i].split()[0].lower()
        bands.append((did, y0, y1))
        L.append(f"  - id: {did}")
        L.append(f"    name: {names[i]}")
        L.append(f"    polygon: [[{_g(x0)}, {_g(y0)}], [{_g(x1)}, {_g(y0)}], "
                 f"[{_g(x1)}, {_g(y1)}], [{_g(x0)}, {_g(y1)}]]")
        L.append(f"    label_anchor: [{_g(x0 + 0.3)}, {_g(y0 + 0.3)}]")
        L.append("    rotation: 0")
    L.append("")

    def _zone_for(wy):
        for did, y0, y1 in bands:
            if y0 <= wy <= y1:
                return did
        return bands[0][0] if wy < bands[0][1] else bands[-1][0]

    # rooms
    L.append("rooms:")
    for r in rooms:
        wx, wy, n = pos[r["id"]]
        w, h = footprint(r["id"], hub, lms, n)
        if r["id"] == hub:
            style, sym = "landmark", "※"
        elif r["id"] in lms:
            style, sym = "temple", "T"
        else:
            style, sym = "civic", "§"
        L.append(f'  - {{id: {r["id"]}, slug: "{r["slug"]}", name: "{r["name"]}", '
                 f'zone: {_zone_for(wy)}, '
                 f'x: {_g(wx)}, y: {_g(wy)}, w: {_g(w)}, h: {_g(h)}, '
                 f'style: {style}, symbol: "{sym}"}}')
    L.append("")

    # exits + exit_paths (L-bend corridors)
    L.append("exits:")
    for a, b in entry["exits"]:
        if a in by_id and b in by_id:
            L.append(f"  - [{a}, {b}]")
    L.append("")
    L.append("exit_paths:")
    for a, b in entry["exits"]:
        if a not in by_id or b not in by_id:
            continue
        ax, ay, _ = pos[a]
        bx, by, _ = pos[b]
        # L-bend: along A's row to B's column, then to B
        path = [(ax, ay), (bx, ay), (bx, by)]
        # collapse collinear duplicates
        pts = []
        for p in path:
            if not pts or (abs(pts[-1][0] - p[0]) > 1e-6 or abs(pts[-1][1] - p[1]) > 1e-6):
                pts.append(p)
        ptstr = ", ".join(f"[{_g(px)}, {_g(py)}]" for px, py in pts)
        L.append(f'  "{a}-{b}": {{kind: corridor, path: [{ptstr}], width: 0.26}}')
    L.append("")

    # landmarks
    L.append("landmarks:")
    for lid in (entry.get("landmark_ids") or []):
        if lid not in by_id:
            continue
        wx, wy, _ = pos[lid]
        r = by_id[lid]
        ident = r["slug"].split("_")[-1] or f"lm{lid}"
        L.append(f'  - {{id: {ident}, icon: palace, name: "{r["name"]}", '
                 f'pos: [{_g(wx)}, {_g(wy)}], min_zoom: 2, max_zoom: 3}}')
    L.append("")
    return "\n".join(L)


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--spec", default="static/tools/_interior_test/interiors_spec.json")
    ap.add_argument("--only", default="", help="comma-separated keys to generate")
    a = ap.parse_args(argv)
    spec = json.loads(Path(a.spec).read_text(encoding="utf-8"))
    only = {k.strip() for k in a.only.split(",") if k.strip()}
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    made = []
    for entry in spec["interiors"]:
        if only and entry["key"] not in only:
            continue
        text = gen(entry)
        out = OUT_DIR / f"{entry['key']}.yaml"
        out.write_text(text + "\n", encoding="utf-8")
        made.append(out.name)
        print(f"  wrote {out}  ({len(entry['rooms'])} rooms, "
              f"{len(entry['exits'])} exits, {len(entry.get('landmark_ids') or [])} landmarks)")
    print(f"[interior-zonemap] generated {len(made)} zone-map(s): {', '.join(made)}")


if __name__ == "__main__":
    main()
